name: ESLint Check

on: [workflow_dispatch, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref }}

      - name: pnpm install
        working-directory: .
        run: pnpm i

      - name: Run Lint
        run: pnpm lint --no-fix
